# Generated by Django 5.0.2 on 2024-02-11 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Qoutes',
            new_name='Quotes',
        ),
        migrations.AlterField(
            model_name='authors',
            name='born_location',
            field=models.CharField(max_length=25, unique=True),
        ),
        migrations.AlterField(
            model_name='authors',
            name='fullname',
            field=models.CharField(max_length=25, unique=True),
        ),
    ]
