# Generated by Django 5.0.2 on 2024-02-12 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_remove_authors_create_remove_quotes_create'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authors',
            name='born_location',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
